[package]
name = "day2"
version = "0.1.0"
authors = ["William Ehlhardt <williamehlhardt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple-error = "0.2.2"
